### ISSUE TITLE
Versioning is done via filenames

### ISSUE THREAD

**Issue by Betaminos** [ruineka/xPlayerOS#15]
Hey there,

thank you for those scripts.
There is a minor issue with the way that file versioning is done here, as the filenames contain "v0.2".
![image](https://user-images.githubusercontent.com/1180151/157044820-ddfed402-8d81-43b5-8342-d35715833763.png)

As GitHub is able to version the files on its own, it makes more sense to have the real filename without the file version.
This way, newer versions will automatically have the same filename as the older version, allowing for other scripts / setups on the user's side to work after an update.

Thank you for your consideration :)

**Comment by ruineka** [comment]
> Hey there,
> 
> thank you for those scripts. There is a minor issue with the way that file versioning is done here, as the filenames contain "v0.2". ![image](https://user-images.githubusercontent.com/1180151/157044820-ddfed402-8d81-43b5-8342-d35715833763.png)
> 
> As GitHub is able to version the files on its own, it makes more sense to have the real filename without the file version. This way, newer versions will automatically have the same filename as the older version, allowing for other scripts / setups on the user's side to work after an update.
> 
> Thank you for your consideration :)

Thanks for the feedback, I've renamed the files as requested.
