### ISSUE TITLE
[Bug] "Switch to Desktop" hangs

### ISSUE THREAD

**Issue by MateyBoi** [ruineka/xPlayerOS#8]
User story
[As a] gamer
[I want] to switch to a chosen DE
[So that] I can carry out tasks outside of SteamDeck UI

User Acceptance Criteria
[Given] a user currently has SteamDeck UI running
[Then] switch to the chosen DE
[When] a user clicks "Switch to Desktop" in the power menu

**Comment by ruineka** [comment]
I'll need to look into this but I think this is because on the Steam Deck the Steam client IS the DE, so when you "Switch to Desktop" it goes to the KDE plasma session.

**Comment by ruineka** [comment]
Should be fixed now.
